<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Divisi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Divisi_model');
        $this->load->model('Kantor_model');
    }

    /*
     * Listing of divisi
     */
    function index()
    {
        $data['divisi'] = $this->Divisi_model->get_all_divisi();
        $data['all_kantor'] = $this->Kantor_model->get_all_kantor();

        $data['_view'] = 'divisi/index';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/divisi/index',$data);
        $this->load->view('templates/dashboard/footer');

    }

    /*
     * Adding a new divisi
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
		$this->form_validation->set_rules('gedung','Gedung','required|max_length[50]');
		$this->form_validation->set_rules('lantai','Lantai','required|integer');
		$this->form_validation->set_rules('id_kantor','Id Kantor','required|integer');

		if($this->form_validation->run())
        {
            $params = array(
				'id_kantor' => $this->input->post('id_kantor'),
				'nama' => $this->input->post('nama'),
				'gedung' => $this->input->post('gedung'),
				'lantai' => $this->input->post('lantai'),
            );

            $divisi_id = $this->Divisi_model->add_divisi($params);
            redirect('divisi/index');
        }
        else
        {
			$this->load->model('Kantor_model');
			$data['all_kantor'] = $this->Kantor_model->get_all_kantor();

            $data['_view'] = 'divisi/add';
            $this->load->view('pages/divisi/add',$data);
        }
    }

    /*
     * Editing a divisi
     */
    function edit($id_divisi)
    {
        // check if the divisi exists before trying to edit it
        $data['divisi'] = $this->Divisi_model->get_divisi($id_divisi);

        if(isset($data['divisi']['id_divisi']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
			$this->form_validation->set_rules('gedung','Gedung','required|max_length[50]');
			$this->form_validation->set_rules('lantai','Lantai','required|integer');
			$this->form_validation->set_rules('id_kantor','Id Kantor','required|integer');

			if($this->form_validation->run())
            {
                $params = array(
					'id_kantor' => $this->input->post('id_kantor'),
					'nama' => $this->input->post('nama'),
					'gedung' => $this->input->post('gedung'),
					'lantai' => $this->input->post('lantai'),
                );

                $this->Divisi_model->update_divisi($id_divisi,$params);
                redirect('divisi/index');
            }
            else
            {
				$this->load->model('Kantor_model');
				$data['all_kantor'] = $this->Kantor_model->get_all_kantor();

                $data['_view'] = 'divisi/edit';
                $this->load->view('pages/divisi/edit',$data);
            }
        }
        else
            show_error('The divisi you are trying to edit does not exist.');
    }

    /*
     * Deleting divisi
     */
    function remove($id_divisi)
    {
        $divisi = $this->Divisi_model->get_divisi($id_divisi);

        // check if the divisi exists before trying to delete it
        if(isset($divisi['id_divisi']))
        {
            $this->Divisi_model->delete_divisi($id_divisi);
            redirect('divisi/index');
        }
        else
            show_error('The divisi you are trying to delete does not exist.');
    }

}
