<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Expired extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Expired_model');
    }

    function index()
    {
        $data['expired'] = $this->Expired_model->get_all_expired();
        
        $data['_view'] = 'expired/index';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/expired/index',$data);
        $this->load->view('templates/dashboard/footer');
    }
}