<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Expired extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Expired_model');
        $this->load->model('Inventory_model');
    }

    function index()
    {
        $data['inventory'] = $this->Inventory_model->get_all_inventory();
        $data['tidakhabis'] = $this->Expired_model->join();
        // $from = new DateTime($data['tanggal']);
        $data['date2'] = new DateTime();
        
        // $age = $from->diff($to)->y . "years and " . $from->diff($to)->m . " months.";
        // echo $age;

        $data['_view'] = 'expired/index';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        // $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/expired/index',$data);
        $this->load->view('templates/dashboard/footer');
    }
}