<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Inventories extends CI_Controller{
        function __construct(){
		parent::__construct();		
		$this->load->model('inventory_model');
	}
	function index(){
        $data['inventory'] = $this->inventory_model->ambil_data()->result();
       
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/inventory/index',$data);
        $this->load->view('templates/dashboard/footer');
	
        }

    function tambah(){
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/inventory/input.php');
        $this->load->view('templates/dashboard/footer');
        
	}
 
	function tambah_aksi(){
        
		$nama = $this->input->post('nama');
		$jenis = $this->input->post('jenis');
        $merk = $this->input->post('merk');
        $nama_divisi_pengada = $this->input->post('nama_divisi_pengada');
        $id_divisi_pengada = $this->input->post('id_divisi_pengada');
        $pekerjaan = $this->input->post('kategori'); 
        
        $data = array(
			'nama' => $nama,
			'jenis' => $jenis,
            'merk' => $merk,
			'nama_divisi_pengada' => $nama_divisi_pengada,
			'kategori' => $kategori,
			);
		$this->m_data->input_data($data,'inventory');
		redirect('inventories/index');
        }

    function hapus($id_inventory){
		$where = array('id_inventory' => $id_inventory);
		$this->m_data->hapus_data($where,'inventory');
		redirect('inventories/index');
        }

    function edit($id_inventory){
		$where = array('id_inventory' => $id_inventory);
		$data['inventory'] = $this->inventory_model->edit_data($where,'inventory')->result();
		$this->load->view('pages/inventory/edit.php',$data);
    }
    function update(){
        $id_inventory = $this->input->post('id_inventory');
        $nama = $this->input->post('nama');
        $jenis = $this->input->post('jenis');        
        $merk = $this->input->post('merk');
        $nama_divisi_pengada = $this->input->post('nama_divisi_pengada');
        $kategori = $this->input->post('kategori');
 
        $data = array(
            'nama' => $nama,
			'jenis' => $jenis,
            'merk' => $merk,
			'nama_divisi_pengada' => $nama_divisi_pengada,
			'kategori' => $kategori,
        );
 
        $where = array(
                'id_inventory' => $id_inventory
        );
 
        $this->inventory_model->update_data($where,$data,'inventory');
        redirect('inventories/index');
    }
}