<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Kantor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata('status') != "login"){
          redirect('');
          }
        $this->load->model('Kantor_model');
    }

    /*
     * Adding a new kantor
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_kantor','Nama','required|max_length[50]');
		$this->form_validation->set_rules('alamat','Alamat','required|max_length[191]');
		$this->form_validation->set_rules('status','Status','required|integer');

		if($this->form_validation->run())
        {
            $params = array(
				'nama_kantor' => $this->input->post('nama_kantor'),
				'alamat' => $this->input->post('alamat'),
				'status' => $this->input->post('status'),
            );

            $kantor_id = $this->Kantor_model->add_kantor($params);
            redirect('manage/kantor');
        }
        // else
        // {
        //     $data['_view'] = 'kantor/add';
        //     $this->load->view('pages/kantor/add',$data);
        // }
    }

    /*
     * Editing a kantor
     */
    function edit($id_kantor)
    {
        // check if the kantor exists before trying to edit it
        $data['kantor'] = $this->Kantor_model->get_kantor($id_kantor);

        if(isset($data['kantor']['id_kantor']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_kantor','Nama','required|max_length[50]');
			$this->form_validation->set_rules('alamat','Alamat','required|max_length[191]');
			$this->form_validation->set_rules('status','Status','required|integer');

			if($this->form_validation->run())
            {
                $params = array(
					'nama_kantor' => $this->input->post('nama_kantor'),
					'alamat' => $this->input->post('alamat'),
					'status' => $this->input->post('status'),
                );

                $this->Kantor_model->update_kantor($id_kantor,$params);
                redirect('manage/kantor');
            }
            else
            {
                $data['_view'] = 'kantor/edit';
                $this->load->view('pages/kantor/edit',$data);
            }
        }
        else
            show_error('The kantor you are trying to edit does not exist.');
    }

    /*
     * Deleting kantor
     */
    function remove($id_kantor)
    {
        $kantor = $this->Kantor_model->get_kantor($id_kantor);

        // check if the kantor exists before trying to delete it
        if(isset($kantor['id_kantor']))
        {
            $this->Kantor_model->delete_kantor($id_kantor);
            redirect('manage/kantor');
        }
        else
            show_error('The kantor you are trying to delete does not exist.');
    }

}
