<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kebutuhan extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        if($this->session->userdata('status') != "login"){
            redirect('');
          }
          
        $this->load->model('Kebutuhan_model');
        $this->load->model('Divisi_model');
        $this->load->model('Admin_model');
    } 

    /*
     * Listing of beli
     */
    function index()
    {
        $data['kebutuhan'] = $this->Kebutuhan_model->get_all_kebutuhan();
        $data['all_divisi'] = $this->Divisi_model->get_all_divisi();
        $data['all_user'] = $this->Admin_model->get_all_admin();
        
        $data['_view'] = 'kebutuhan/index';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/kebutuhan/index',$data);
        $this->load->view('templates/dashboard/footer');
    }

    /*
     * Adding a new beli
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_barang','Nama Barang','required');
		$this->form_validation->set_rules('jumlah','Jumlah','required|integer');
        $id_user = $this->session->userdata('id_user');
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_divisi' => $this->input->post('id_divisi'),
				'nama_barang' => $this->input->post('nama_barang'),
                'jumlah' => $this->input->post('jumlah'),
                'id_user' =>  $id_user,
            );
            
            $kebutuhan_id = $this->Kebutuhan_model->add_kebutuhan($params);
            redirect('kebutuhan/index');
        }
        else
        {
			$this->load->model('Divisi_model');
            $data['all_divisi'] = $this->Divisi_model->get_all_divisi();
            
            $data['_view'] = 'kebutuhan/add';
            $this->load->view('pages/kebutuhan/add',$data);
        }
    }  

    /*
     * Editing a beli
     */
    function edit($id_kebutuhan)
    {   
        // check if the beli exists before trying to edit it
        $data['kebutuhan'] = $this->Kebutuhan_model->get_kebutuhan($id_kebutuhan);
        
        if(isset($data['kebutuhan']['id_kebutuhan']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_barang','Nama Barang','required');
			$this->form_validation->set_rules('jumlah','Jumlah','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_divisi' => $this->input->post('id_divisi'),
					'nama_barang' => $this->input->post('nama_barang'),
					'jumlah' => $this->input->post('jumlah'),
                );

                $this->Kebutuhan_model->update_kebutuhan($id_kebutuhan,$params);            
                redirect('kebutuhan/index');
            }
            else
            {
				$this->load->model('Divisi_model');
				$data['all_divisi'] = $this->Divisi_model->get_all_divisi();

                $data['_view'] = 'kebutuhan/edit';
                $this->load->view('pages/kebutuhan/edit',$data);
            }
        }
        else
            show_error('The beli you are trying to edit does not exist.');
    } 

    /*
     * Deleting beli
     */
    function remove($id_kebutuhan)
    {
        $kebutuhan = $this->Kebutuhan_model->get_kebutuhan($id_kebutuhan);

        // check if the beli exists before trying to delete it
        if(isset($kebutuhan['id_kebutuhan']))
        {
            $this->Kebutuhan_model->delete_kebutuhan($id_kebutuhan);
            redirect('kebutuhan/index');
        }
        else
            show_error('The beli you are trying to delete does not exist.');
    }
    
}
