<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Manage extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata('status') != "login"){
            redirect('');
          }
        $this->load->model('Divisi_model');
        $this->load->model('admin_model');
        $this->load->model('Kantor_model');
    }

    function kantor()
    {
      if($this->session->userdata('level') == 1){
        $id_user = $this->session->userdata('id_user');
        $data['user'] = $this->admin_model->get_admin($id_user);
        $data['kantor'] = $this->Kantor_model->get_all_kantor();

        $data['_view'] = 'manage/kantor';
        $this->load->view('templates/dashboard/header');
      $this->load->view('templates/dashboard/topbar', $data);
      $this->load->view('templates/dashboard/leftbar', $data);
      $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/manage/kantor',$data);
        $this->load->view('templates/dashboard/footer');
      }
      else {
        redirect('home');
      }
      

    }

    function user()
    {
        if ($this->session->userdata('level') == 1){
          $id_user = $this->session->userdata('id_user');
          $data['user'] = $this->admin_model->get_admin($id_user);
          $by_kantor = $this->input->post('pilih_cabang');
          // $data['user'] = $this->admin_model->get_all_admin();
          $data['all_kantor'] = $this->Kantor_model->get_all_kantor();
          $data['all_divisi'] = $this->Divisi_model->get_all_divisi();
          if($by_kantor == 0){
            $data['records'] = $this->admin_model->get_all_admin_by_kantor();
          }
          else{
            $data['records'] = $this->admin_model->get_admin_by_kantor($by_kantor);
          }

          $data['_view'] = 'manage/user';
          $this->load->view('templates/dashboard/header');
          $this->load->view('templates/dashboard/topbar', $data);
          $this->load->view('templates/dashboard/leftbar', $data);
          $this->load->view('templates/dashboard/rightbar');
          $this->load->view('pages/manage/user',$data);
          $this->load->view('templates/dashboard/footer');
        }
        else{
          redirect('home');
        }
    }

    function divisi()
    {
      if($this->session->userdata('level') == 1){
        $id_user = $this->session->userdata('id_user');
        $data['user'] = $this->admin_model->get_admin($id_user);
        $by_kantor = $this->input->post('pilih_cabang');
        $data['divisi'] = $this->Divisi_model->get_all_divisi();
        $data['all_kantor'] = $this->Kantor_model->get_all_kantor();
        if($by_kantor == 0){
          $data['records'] = $this->Divisi_model->get_all_divisi_by_kantor();
        }
        else{
          $data['records'] = $this->Divisi_model->get_divisi_by_kantor($by_kantor);
        }
        $data['_view'] = 'manage/divisi';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar', $data);
        $this->load->view('templates/dashboard/leftbar', $data);
        // $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/manage/divisi',$data);
        $this->load->view('templates/dashboard/footer');
      }
      else{
        redirect('home');
      }
    }
  }
