<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Manage extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata('status') != "login"){
          redirect('');
          }
        $this->load->model('Divisi_model');
        $this->load->model('admin_model');
        $this->load->model('Kantor_model');
    }

    function kantor()
    {
        $data['kantor'] = $this->Kantor_model->get_all_kantor();

        $data['_view'] = 'manage/kantor';
        $this->load->view('templates/dashboard/header');
      $this->load->view('templates/dashboard/topbar');
      $this->load->view('templates/dashboard/leftbar');
      $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/manage/kantor',$data);
        $this->load->view('templates/dashboard/footer');

    }

    function user()
    {
        $data['user'] = $this->admin_model->get_all_admin();
        $data['all_divisi'] = $this->Divisi_model->get_all_divisi();

        $data['_view'] = 'manage/user';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/manage/user',$data);
        $this->load->view('templates/dashboard/footer');
    }

    function divisi()
    {
        $data['divisi'] = $this->Divisi_model->get_all_divisi();
        $data['all_kantor'] = $this->Kantor_model->get_all_kantor();

        $data['_view'] = 'manage/divisi';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/manage/divisi',$data);
        $this->load->view('templates/dashboard/footer');

    }
  }
