<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pengembalian extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata('status') != "login"){
            redirect('');
        }
        $this->load->model('Expired_model');
        $this->load->model('Inventory_model');
        $this->load->model('Divisi_model');
        $this->load->model('admin_model');
    }

    function index()
    {
        $id_user = $this->session->userdata('id_user');
        $data['user'] = $this->admin_model->get_admin($id_user);
        $data['inventory'] = $this->Inventory_model->get_all_inventory();
        $data['tidakhabis'] = $this->Expired_model->join_pengembalian();
        $this->load->model('Divisi_model');

        $data['all_divisi'] = $this->Divisi_model->get_all_divisi();

        $data['_view'] = 'pengembalian/index';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar', $data);
        $this->load->view('templates/dashboard/leftbar', $data);
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/pengembalian/index',$data);
        $this->load->view('templates/dashboard/footer');
    }
}
