<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Penjualan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata('status') != "login"){
            redirect('');
            }
        $this->load->model('Expired_model');
        $this->load->model('Inventory_model');
    }

    function index()
    {
        $data['inventory'] = $this->Inventory_model->get_all_inventory();
        $data['tidakhabis'] = $this->Expired_model->join_penjualan();

        $data['_view'] = 'penjualan/index';
        $this->load->view('templates/dashboard/header');
        $this->load->view('templates/dashboard/topbar');
        $this->load->view('templates/dashboard/leftbar');
        $this->load->view('templates/dashboard/rightbar');
        $this->load->view('pages/penjualan/index',$data);
        $this->load->view('templates/dashboard/footer');
    }
}
