<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Divisi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_divisi_by_kantor($by_kantor){
        $this->db->select('*');
        $this->db->from('divisi');
        $this->db->order_by('nama_divisi', 'asc');
        $this->db->join('kantor', 'kantor.id_kantor = divisi.id_kantor');
        $this->db->where('kantor.id_kantor', $by_kantor);
        $query = $this->db->get();
          return $query->result_array();
    }
    /*
     * Get divisi by id_divisi
     */
    function get_divisi($id_divisi)
    {
        return $this->db->get_where('divisi',array('id_divisi'=>$id_divisi))->row_array();
    }

    /*
     * Get all divisi
     */
    function get_all_divisi()
    {
        $this->db->order_by('nama_divisi', 'asc');
        return $this->db->get('divisi')->result_array();
    }

    function get_all_divisi_by_kantor()
    {
        $this->db->select('*');
        $this->db->from('divisi');
        $this->db->join('kantor', 'kantor.id_kantor = divisi.id_kantor');
        $this->db->order_by('nama_kantor', 'asc');
        $query = $this->db->get();
          return $query->result_array();
    }

    /*
     * function to add new divisi
     */
    function add_divisi($params)
    {
        $this->db->insert('divisi',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update divisi
     */
    function update_divisi($id_divisi,$params)
    {
        $this->db->where('id_divisi',$id_divisi);
        return $this->db->update('divisi',$params);
    }

    /*
     * function to delete divisi
     */
    function delete_divisi($id_divisi)
    {
        return $this->db->delete('divisi',array('id_divisi'=>$id_divisi));
    }
}
