<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Eventlog_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get eventlog by id_event
     */
    function get_eventlog($id_event)
    {
        return $this->db->get_where('eventlog',array('id_event'=>$id_event))->row_array();
    }
        
    /*
     * Get all eventlog
     */
    function get_all_eventlog()
    {
        $this->db->order_by('id_event', 'desc');
        return $this->db->get('eventlog')->result_array();
    }
        
    /*
     * function to add new eventlog
     */
    function add_eventlog($params)
    {
        $this->db->insert('eventlog',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update eventlog
     */
    function update_eventlog($id_event,$params)
    {
        $this->db->where('id_event',$id_event);
        return $this->db->update('eventlog',$params);
    }
    
    /*
     * function to delete eventlog
     */
    function delete_eventlog($id_event)
    {
        return $this->db->delete('eventlog',array('id_event'=>$id_event));
    }
}
