<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Expired_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get beli by id_beli
     */
    function get_kebutuhan($id_kebutuhan)
    {
        return $this->db->get_where('kebutuhan',array('id_kebutuhan'=>$id_kebutuhan))->row_array();
    }
        
    /*
     * Get all beli
     */
    function get_all_expired()
    {
        $this->db->order_by('id_inventory', 'desc');
        return $this->db->get('tidakhabispakai')->result_array();
    }
}
