<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Kantor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get kantor by id_kantor
     */
    function get_kantor($id_kantor)
    {
        return $this->db->get_where('kantor',array('id_kantor'=>$id_kantor))->row_array();
    }
    /*
     * Get all kantor
     */
     function get_kantor_by_divisi($id_divisi){
       $this->db->select('*');
       $this->db->from('divisi');
       $this->db->where('divisi.id_divisi', $id_divisi);
       $query = $this->db->get();
         return $query->result_array();
     }

    function get_all_kantor()
    {
        $this->db->order_by('nama_kantor', 'asc');
        return $this->db->get('kantor')->result_array();
    }

    /*
     * function to add new kantor
     */
    function add_kantor($params)
    {
        $this->db->insert('kantor',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update kantor
     */
    function update_kantor($id_kantor,$params)
    {
        $this->db->where('id_kantor',$id_kantor);
        return $this->db->update('kantor',$params);
    }

    /*
     * function to delete kantor
     */
    function delete_kantor($id_kantor)
    {
        return $this->db->delete('kantor',array('id_kantor'=>$id_kantor));
    }
}
