<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kebutuhan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get beli by id_beli
     */
    function get_kebutuhan($id_kebutuhan)
    {
        return $this->db->get_where('kebutuhan',array('id_kebutuhan'=>$id_kebutuhan))->row_array();
    }
        
    /*
     * Get all beli
     */
    function get_all_kebutuhan()
    {
        $this->db->order_by('id_kebutuhan', 'desc');
        return $this->db->get('kebutuhan')->result_array();
    }
        
    /*
     * function to add new beli
     */
    function add_kebutuhan($params)
    {
        $this->db->insert('kebutuhan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update beli
     */
    function update_beli($id_beli,$params)
    {
        $this->db->where('id_beli',$id_beli);
        return $this->db->update('beli',$params);
    }
    
    /*
     * function to delete beli
     */
    function delete_beli($id_beli)
    {
        return $this->db->delete('beli',array('id_beli'=>$id_beli));
    }
}
