<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Kebutuhan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get beli by id_beli
     */
    function get_kebutuhan($id_kebutuhan)
    {
        return $this->db->get_where('kebutuhan',array('id_kebutuhan'=>$id_kebutuhan))->row_array();
    }

    /*
     * Get all beli
     */
    function get_all_kebutuhan()
    {
        $this->db->order_by('id_kebutuhan', 'desc');
        return $this->db->get('kebutuhan')->result_array();
    }

    function get_kebutuhan_by_kantor($by_kantor){
        $this->db->select('*');
        $this->db->from('kebutuhan');
        $this->db->join('divisi', 'kebutuhan.id_divisi = divisi.id_divisi');
        $this->db->join('kantor', 'divisi.id_kantor = kantor.id_kantor');
        $this->db->where('kantor.id_kantor', $by_kantor);
        $query = $this->db->get();
          return $query->result_array();
    }

    function get_kebutuhan_by_divisi($id_user){
      $this->db->select('*');
      $this->db->from('kebutuhan');
      $this->db->where('kebutuhan.id_user', $id_user);
      $query = $this->db->get();
        return $query->result_array();
    }

    /*
     * function to add new beli
     */
    function add_kebutuhan($params)
    {
        $this->db->insert('kebutuhan',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update beli
     */
    function update_kebutuhan($id_kebutuhan,$params)
    {
        $this->db->where('id_kebutuhan',$id_kebutuhan);
        return $this->db->update('kebutuhan',$params);
    }

    /*
     * function to delete beli
     */
    function delete_kebutuhan($id_kebutuhan)
    {
        return $this->db->delete('kebutuhan',array('id_kebutuhan'=>$id_kebutuhan));
    }
}
