<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pemeliharaan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pemeliharaan by id_pemeliharaan
     */
    function get_pemeliharaan($id_pemeliharaan)
    {
        return $this->db->get_where('pemeliharaan',array('id_pemeliharaan'=>$id_pemeliharaan))->row_array();
    }

    /*
     * Get all pemeliharaan
     */

     function get_pemeliharaan_by_kantor($by_kantor)
     {
       $this->db->select('*');
       $this->db->from('pemeliharaan');
       $this->db->join('inventory', 'pemeliharaan.id_inventory = inventory.id_inventory');
       $this->db->join('divisi', 'divisi.id_divisi = inventory.id_divisi_penerima');
       $this->db->join('kantor', 'divisi.id_kantor = kantor.id_kantor');
       $this->db->where('kantor.id_kantor', $by_kantor);
       $query = $this->db->get();
         return $query->result_array();
     }
     
    function get_all_pemeliharaan()
    {
        $this->db->order_by('id_pemeliharaan', 'desc');
        return $this->db->get('pemeliharaan')->result_array();
    }

    /*
     * function to add new pemeliharaan
     */
    function add_pemeliharaan($params)
    {
        $this->db->insert('pemeliharaan',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update pemeliharaan
     */
    function update_pemeliharaan($id_pemeliharaan,$params)
    {
        $this->db->where('id_pemeliharaan',$id_pemeliharaan);
        return $this->db->update('pemeliharaan',$params);
    }

    /*
     * function to delete pemeliharaan
     */
    function delete_pemeliharaan($id_pemeliharaan)
    {
        return $this->db->delete('pemeliharaan',array('id_pemeliharaan'=>$id_pemeliharaan));
    }

    function get_rawat($id_inventory)
    {
        $this->db->select('*');
        $this->db->from('pemeliharaan');
        $this->db->where('pemeliharaan.id_inventory',$id_inventory);
        $query = $this->db->get();
        return $query->result();
    }
}
