<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sewa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sewa by id_sewa
     */
    function get_sewa($id_sewa)
    {
        return $this->db->get_where('sewa',array('id_sewa'=>$id_sewa))->row_array();
    }
        
    /*
     * Get all sewa
     */
    function get_all_sewa()
    {
        $this->db->order_by('id_sewa', 'desc');
        return $this->db->get('sewa')->result_array();
    }
        
    /*
     * function to add new sewa
     */
    function add_sewa($params)
    {
        $this->db->insert('sewa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sewa
     */
    function update_sewa($id_sewa,$params)
    {
        $this->db->where('id_sewa',$id_sewa);
        return $this->db->update('sewa',$params);
    }
    
    /*
     * function to delete sewa
     */
    function delete_sewa($id_sewa)
    {
        return $this->db->delete('sewa',array('id_sewa'=>$id_sewa));
    }
}
