<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Supplier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get supplier by id_supplier
     */
    function get_supplier($id_supplier)
    {
        return $this->db->get_where('supplier',array('id_supplier'=>$id_supplier))->row_array();
    }
        
    /*
     * Get all supplier
     */
    function get_all_supplier()
    {
        $this->db->order_by('id_supplier', 'desc');
        return $this->db->get('supplier')->result_array();
    }
        
    /*
     * function to add new supplier
     */
    function add_supplier($params)
    {
        $this->db->insert('supplier',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update supplier
     */
    function update_supplier($id_supplier,$params)
    {
        $this->db->where('id_supplier',$id_supplier);
        return $this->db->update('supplier',$params);
    }
    
    /*
     * function to delete supplier
     */
    function delete_supplier($id_supplier)
    {
        return $this->db->delete('supplier',array('id_supplier'=>$id_supplier));
    }
}
