<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vendor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vendor by id_vendor
     */
    function get_vendor($id_vendor)
    {
        return $this->db->get_where('vendor',array('id_vendor'=>$id_vendor))->row_array();
    }
        
    /*
     * Get all vendor
     */
    function get_all_vendor()
    {
        $this->db->order_by('id_vendor', 'desc');
        return $this->db->get('vendor')->result_array();
    }
        
    /*
     * function to add new vendor
     */
    function add_vendor($params)
    {
        $this->db->insert('vendor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vendor
     */
    function update_vendor($id_vendor,$params)
    {
        $this->db->where('id_vendor',$id_vendor);
        return $this->db->update('vendor',$params);
    }
    
    /*
     * function to delete vendor
     */
    function delete_vendor($id_vendor)
    {
        return $this->db->delete('vendor',array('id_vendor'=>$id_vendor));
    }
}
